### ISSUE TITLE
Missing typing declarations

### ISSUE THREAD

**Issue by slavafomin** [rollup/rollup-plugin-typescript#140] opened 2019-06-14 11:19 UTC
Hello!

Thank you for this great library!

However, it looks really weird when plugin, which integrates TypeScript misses it's own typing declarations.

**Comment by maxmilton** [comment] 2019-07-06 02:19
Duplicate of https://github.com/rollup/rollup-plugin-typescript/issues/54

**Comment by slavafomin** [comment] 2019-07-08 09:46
> Duplicate of #54

I don't think so. This issue is about `rollup-plugin-typescript` lacking it's own type declarations.

**Comment by shellscape** [comment] 2019-11-24 17:01
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Closed as completed by shellscape** 2019-11-24 17:01 UTC

**Comment by slavafomin** [comment] 2019-11-24 19:53
@shellscape please, keep it

**Comment by shellscape** [comment] 2019-11-24 20:57
@slavafomin thanks for the reply. #138 should satisfy this issue. Please have a look and let me know if you agree.
