### ISSUE TITLE
Property shorthand does not transpile

### ISSUE THREAD

**Issue by shantanuraj** [rollup/rollup-plugin-typescript#40] opened 2016-04-15 13:48 UTC
I demoed it in the following [gist](https://gist.github.com/shantanuraj/7d9c4857fbe5e893f815aa934fff6fef)

So basically this

`const f = val => ({ val })`

should transpile to

`var f = function (val) { return ({ val: val }); };`

but transpiles to

`var f = function (val) { return ({ val }); };`

Edit

Renamed Destructuring to Property shorthand

**Comment by Victorystick** [comment] 2016-04-15 14:05
Ah. This is actually _property shorthand_, not _destructuring_.

``` ts
function foo( object ) {
  // object _destructuring_, extracting properties by name
  const { property } = object;

  // object _creation_, using a property shorthand
  return { property };
}
```

And I'm afraid the bug is in the TypeScript compiler itself. I thought I had fixed the shorthand properties in Microsoft/TypeScript#7442, but something seems to be missing.

**Comment by shantanuraj** [comment] 2016-04-15 14:25
Updated the title to property shorthand, this seems to be a really weird case, using the typescript compiler 1.8.7 or 1.8.10 directly, the file is transpiled correctly.

Also I am not sure on how to override the typescript version used by the plugin what I am doing is

```
const typescript = require('rollup-plugin-typescript')
const ts = require('typescript')

module.exports = {
  entry: 'index.ts',
  sourceMap: false,
  format: 'es6',
  plugins: [
    typescript({typescript: ts})
  ],
  dest: 'bundle.js'
}
```

But I get this error

```
rollup-plugin-typescript: Unknown compiler option 'typescript'.
rollup-plugin-typescript: Couldn't process compiler options
```

**Comment by Victorystick** [comment] 2016-04-19 08:44
@shantanuraj I've released `0.7.1` which shouldn't display that error. I'll look into the reason for the regression of shorthand properties.

**Comment by TimMensch** [comment] 2016-08-12 23:08
@Victorystick I just wasted about four hours trying to track down why tests were suddenly failing, and it turned out to be this bug causing the problem. I also verified that it fails when using TypeScript 1.8.10, as per the readme, but TypeScript itself does the compile without issue.

Any updates?

**Comment by TimMensch** [comment] 2016-08-13 04:53
For future reference:

This is being caused deep in TypeScript. Version 1.8.10 of tsc won't let you set es2015 modules with an es5 target at the same time, but you can set that combination from the JavaScript API, and rollup-plugin-typescript does in fact force those settings. 

When rollup-plugin-typescript is hacked to use the commonjs module flag, the problem is fixed. And it turns out that when you force TypeScript 2.0.0 (as per the readme for custom versions of TypeScript), it also fixes the problem.

So either TypeScript itself needs to be hacked or upgraded to 2.0.0. I'm taking the latter strategy as a workaround. All my code still compiles and seems to work so far.

**Comment by PaulBGD** [comment] 2017-05-23 04:13
TypeScript error, closing.

**Closed as completed by PaulBGD** 2017-05-23 04:13 UTC
