### ISSUE TITLE
No type checking - Ignores errors in the code

### ISSUE THREAD

**Issue by ghost** [rollup/rollup-plugin-typescript#51] opened 2016-07-17 23:29 UTC
With default TSC you can't transpile if there are issues in the code. With this plugin everything seems to be transpiled even with errors. No default type checking?

Example

``` js
function foo(name: string): void {}
foo([]); // array and valid with this plugin
```

In VSCode I get this message: `Argument of type 'never[]' is not assignable to parameter of type 'string'.`

But Rollup ignores it and bundle just fine!

**Comment by Victorystick** [comment] 2016-07-18 21:19
Yes, I'm aware of the issue. I haven't gotten around to it mainly because I intercept typing errors through the editor, and only build with the plugin. It's definitely at the top of my TODO though.

Closing as duplicate of #43.

**Closed as completed by Victorystick** 2016-07-18 21:19 UTC
Labels: duplicate
