### ISSUE TITLE
types and typeRoots in the tsconfig generate rollup error

### ISSUE THREAD

**Issue by SebasAcevedo** [rollup/rollup-plugin-typescript#74] opened 2016-11-15 01:41 UTC
If you put types and/or typeRoots in your tsconfig, rollup will raise the folloring error:

Unknown compiler option 'typeRoots'
Unknown compiler option 'types'
Couldn't process compiler options

**Comment by TimeWaitsForNoOne** [comment] 2016-11-24 10:15
upgrade your typescript first, then use the config options typescript: require('typescript') @SebasAcevedo

**Comment by PaulBGD** [comment] 2017-05-23 04:11
Let me know if this needs to be reopened, but looks like @TimeWaitsForNoOne found the fix.

**Comment by LukasBombach** [comment] 2018-01-15 20:26
The issue is still there, this is my `tsconfig.json`

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ES6",
    "jsx": "react",
    "sourceMap": true,
    "noImplicitAny": true,
    "outDir": "./dist",
    "removeComments": true,
    "typeRoots": ["./node_modules/@types"]
  },
  "include": ["src/**/*", "tests/**/*"],
  "exclude": ["node_modules", "**/*-spec.ts"]
}
```

This is the command I execute: `rollup -c`

**Comment by shellscape** [comment] 2019-11-24 16:47
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Closed as completed by shellscape** 2019-11-24 16:47 UTC
